const KZN_DATA = {
  locations: [
    {
      id: "krantzkloof",
      name: "Krantzkloof Nature Reserve",
      slug: "krantzkloof-nature-reserve",
      tagline: "Dramatic gorge, crowned eagles & cascading falls",
      description: "Krantzkloof is one of KZN's most spectacular reserves, featuring the magnificent Molweni River gorge, Kloof Falls, and dense coastal scarp forest. Home to crowned eagles, forest buzzards, and over 300 bird species. The towering cliffs and river valleys offer some of the most challenging and rewarding trails in Durban.",
      hectares: 484,
      location: "Kloof / Pinetown",
      management: "Ezemvelo KZN Wildlife",
      coordinates: { lat: -29.7784, lng: 30.8369 },
      payment_method: "Card Only",
      entry_fee_adult: 60,
      entry_fee_child: 21,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Fenced, guarded lots at Kloof Falls and Nkutu Picnic Sites",
      hours: "07:00 – 17:00 Daily",
      phone: "+27 31 764 3514",
      website: null,
      tags: ["Hiking", "Birdwatching", "Waterfalls", "Gorge", "Photography"],
      hazards: ["Steep cliffs", "Flash floods in gorge", "Slippery paths when wet"],
      regulations: ["No pets allowed", "No alcohol", "No loud music", "No geocaching", "No cash accepted"],
      attractions: ["Kloof Falls", "Molweni River", "Crowned Eagles", "Forest Buzzards", "Beacon Trail"],
      reviews: [
        { user: "TrailRunner_KZN", date: "2026-05-28", safety: 4, parking: 5, cleanliness: 5, cost: 3, environmental: 3, comment: "Stunning reserve. The Molweni trail is challenging but worth every step. Card only at the gate – don't arrive with cash! Gorgeous waterfalls after good rain." },
        { user: "BirdwatcherDbn", date: "2026-05-15", safety: 5, parking: 5, cleanliness: 4, cost: 4, environmental: 3, comment: "Spotted two Crowned Eagles on the ridge trail. Security has improved massively with the new rangers. Highly recommend the early morning walks." },
        { user: "FamilyHikers_ZA", date: "2026-04-30", safety: 4, parking: 4, cleanliness: 4, cost: 4, environmental: 4, comment: "Great family day out. Kids loved the waterfall. Trail was well marked. Bring a credit card – they really do not take cash. Beautiful forest." }
      ],
      alerts: [
        { category: "Flash Flood", severity: "Medium", details: "Molweni River crossing may be impassable after heavy rain. Check conditions at the gate before attempting lower gorge trails.", active: true }
      ],
      photo: "https://loremflickr.com/1000/500/gorge,forest,waterfall/all",
      photoCredit: "Photo: Unsplash",
      images: ["krantzkloof1", "krantzkloof2"],
      featured: true
    },
    {
      id: "giba-gorge",
      name: "Giba Gorge MTB Park",
      slug: "giba-gorge-mtb-park",
      tagline: "World-class single-tracks in a stunning valley",
      description: "Giba Gorge is Durban's premier privately-owned mountain biking destination, featuring over 45km of professionally designed and maintained single-track trails winding through a lush gorge. The park includes a licensed restaurant (Giba Graze Café), bike hire, and pristine ablution facilities. Perfect for trail runners and outdoor enthusiasts too.",
      hectares: null,
      location: "Pinetown / New Germany",
      management: "Private Commercial",
      coordinates: { lat: -29.8012, lng: 30.8756 },
      payment_method: "Cash & Card",
      entry_fee_adult: 70,
      entry_fee_child: 50,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Fully secured, access-controlled gated private parking lot",
      hours: "07:00 – 17:00 (Closed Tuesdays)",
      phone: "+27 31 700 1080",
      website: null,
      tags: ["Mountain Biking", "Trail Running", "Café", "Family", "Dog Friendly"],
      hazards: ["Technical MTB trails – beginners should start on green routes"],
      regulations: ["Dogs must remain on leash at all times", "No outside food or catering", "No alcohol brought in", "No open braais"],
      attractions: ["45km+ single-track network", "Giba Gorge waterfalls", "Giba Graze Café", "Bike hire facilities", "Kids' trails"],
      reviews: [
        { user: "MTBRider_Dbn", date: "2026-05-25", safety: 5, parking: 5, cleanliness: 5, cost: 3, environmental: 5, comment: "Best MTB trails in KZN without question. The new black diamond descent is heart-pumping. Café food is excellent. Worth every cent of the entry fee." },
        { user: "TrailRunner_SA", date: "2026-05-10", safety: 5, parking: 5, cleanliness: 5, cost: 3, environmental: 5, comment: "Ran the full 45km network over two visits. Immaculate trail maintenance. Parking is Fort Knox-level secure. Highly recommend for solo runners." },
        { user: "WeekendAdventurer", date: "2026-04-20", safety: 5, parking: 5, cleanliness: 4, cost: 2, environmental: 5, comment: "Absolutely beautiful gorge. A bit pricey but the infrastructure justifies it. No cash? No problem – tap-and-go available. Bring the whole family." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/mountain,bike,trail/all",
      photoCredit: "Photo: Unsplash",
      images: ["giba1", "giba2"],
      featured: true
    },
    {
      id: "palmiet",
      name: "Palmiet Nature Reserve",
      slug: "palmiet-nature-reserve",
      tagline: "Free urban forest & accessible river walks",
      description: "Palmiet Nature Reserve is Westville's hidden green gem — 90 hectares of dense scarp forest and indigenous bush along the Palmiet River. One of the few free nature reserves in Durban with wheelchair-accessible cement paths near the entrance. Perfect for family walks, birdwatching, and photography.",
      hectares: 90,
      location: "Dawncrest, Westville",
      management: "eThekwini Municipality & Community Committee",
      coordinates: { lat: -29.8285, lng: 30.9012 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Guarded Public Lot",
      parking_notes: "Guarded community lot at Edgecliff Road administrative hall",
      hours: "06:00 – 17:30 Daily",
      phone: "+27 31 265 5487",
      website: null,
      tags: ["Free", "Family", "Birdwatching", "Accessible", "River Walk"],
      hazards: ["Slippery clay slopes after rain", "River crossings can flood after heavy rain", "Fallen trees post-storm"],
      regulations: ["Keep to marked paths", "No littering", "Donations encouraged to support maintenance"],
      attractions: ["Palmiet River", "Scarp forest canopy walks", "Cement accessible paths", "Bird hides", "Picnic spots"],
      reviews: [
        { user: "WestvilleMom", date: "2026-06-01", safety: 4, parking: 4, cleanliness: 4, cost: 5, environmental: 4, comment: "Perfect free Saturday morning walk with the kids. The cement path near the entrance is great for young children. Reserve staff are friendly and helpful." },
        { user: "BirdPhotographer", date: "2026-05-18", safety: 3, parking: 4, cleanliness: 3, cost: 5, environmental: 3, comment: "Beautiful birds but trail maintenance needs attention after recent floods. Some paths blocked by fallen trees. Still worth the visit – and it's FREE!" },
        { user: "MorningWalker_DBN", date: "2026-04-05", safety: 4, parking: 4, cleanliness: 4, cost: 5, environmental: 4, comment: "My daily morning walk spot. River path is magical at dawn. Guard at the gate is very reassuring for solo walkers. Can't believe this is free." }
      ],
      alerts: [
        { category: "Trail Obstruction", severity: "Low", details: "Several fallen trees on the upper river path after recent storms. The lower cement path and entrance trails are fully clear.", active: true }
      ],
      photo: "https://loremflickr.com/1000/500/river,forest,nature/all",
      photoCredit: "Photo: Unsplash",
      images: ["palmiet1", "palmiet2"],
      featured: false
    },
    {
      id: "paradise-valley",
      name: "Paradise Valley Nature Reserve",
      slug: "paradise-valley-nature-reserve",
      tagline: "Historic waterworks & hidden waterfall trail",
      description: "Paradise Valley is one of Durban's most scenic hidden gems, featuring the historic Umbilo Waterworks, a dramatic waterfall trail, and resident blue duikers. The reserve runs along the Umbilo River in Pinetown, offering a cool, forested escape from the city. Note: upstream water pollution means swimming is prohibited.",
      hectares: 135,
      location: "Pinetown",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.8456, lng: 30.8623 },
      payment_method: "Cash & Card",
      entry_fee_adult: 21,
      entry_fee_child: 10,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Secured interior lot; heavily constrained on weekends – arrive early",
      hours: "07:00 – 17:00 Daily",
      phone: "+27 31 700 5000",
      website: null,
      tags: ["Waterfall", "History", "Wildlife", "Photography", "Budget"],
      hazards: ["Upstream water pollution – no swimming", "Weekend parking severely limited", "Highway construction noise"],
      regulations: ["No swimming in river", "No feeding wildlife", "Keep dogs on leash"],
      attractions: ["Historic Umbilo Waterworks", "Waterfall Trail", "Blue Duiker sightings", "Umbilo River path", "Forest canopy"],
      reviews: [
        { user: "HistoryBuff_KZN", date: "2026-05-22", safety: 3, parking: 3, cleanliness: 3, cost: 5, environmental: 2, comment: "The historic waterworks ruins are fascinating. Trail to the waterfall is beautiful. Go on a weekday – weekend parking is chaos and fills up fast." },
        { user: "NaturePhotog_DBN", date: "2026-05-01", safety: 3, parking: 2, cleanliness: 3, cost: 5, environmental: 2, comment: "Spectacular waterfall for photography. Got great duiker shots too. Parking was full on Saturday so had to park on the road outside – not ideal. River water looks dirty." },
        { user: "WalkingClub_ZA", date: "2026-03-15", safety: 4, parking: 3, cleanliness: 3, cost: 5, environmental: 3, comment: "Lovely walk through indigenous forest. Historical infrastructure is unique. Water pollution is a visible problem. Construction noise from the highway is disruptive." }
      ],
      alerts: [
        { category: "Water Pollution", severity: "High", details: "Upstream sewer overflow detected. High E. coli levels in the Umbilo River. Swimming and wading is strictly prohibited until further notice.", active: true }
      ],
      photo: "https://loremflickr.com/1000/500/waterfall,valley,jungle/all",
      photoCredit: "Photo: Unsplash",
      images: ["paradise1", "paradise2"],
      featured: false
    },
    {
      id: "kenneth-stainbank",
      name: "Kenneth Stainbank Nature Reserve",
      slug: "kenneth-stainbank-nature-reserve",
      tagline: "Zebras, impala & bat caves near the city",
      description: "Kenneth Stainbank is Durban's most biodiverse urban nature reserve — 253 hectares of open grasslands and riverine forest in Yellowwood Park, home to resident zebras, impala, wildebeest, and over 200 bird species. The only urban reserve in KZN where you can walk among free-roaming large mammals. Don't leave valuables in your car — cheeky monkeys have learned to open doors!",
      hectares: 253,
      location: "Yellowwood Park, Durban South",
      management: "Ezemvelo KZN Wildlife",
      coordinates: { lat: -29.9156, lng: 30.9234 },
      payment_method: "Cash & Card",
      entry_fee_adult: 60,
      entry_fee_child: 21,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Heavily secured, gated parking lot inside the main entrance – extremely safe",
      hours: "06:00 – 18:00 Daily",
      phone: "+27 31 462 1394",
      website: null,
      tags: ["Wildlife", "Birdwatching", "Walking", "Family", "Zebra"],
      hazards: ["Vervet monkeys can open unlocked car doors – lock everything", "Stay on paths near large mammals"],
      regulations: ["Lock car doors at all times", "No pets allowed", "Stay on marked trails near wildlife", "No feeding animals"],
      attractions: ["Free-roaming Zebra herd", "Impala & Wildebeest", "Over 200 bird species", "Historic bat colony caves", "Riverine forest trails"],
      reviews: [
        { user: "ZebraScout_DBN", date: "2026-05-30", safety: 5, parking: 5, cleanliness: 5, cost: 3, environmental: 5, comment: "Zebras walking right past you on the path! Kids were absolutely amazed. Parking is the most secure in Durban – staff guard the lot personally. Don't forget to lock your car!" },
        { user: "MorningBirdwatcher", date: "2026-05-12", safety: 5, parking: 5, cleanliness: 4, cost: 3, environmental: 5, comment: "Incredible birding. Spotted 34 species in 2 hours. The grassland trails at sunrise are magical with wildebeest in the mist. Security is excellent." },
        { user: "FamilyDay_KZN", date: "2026-04-18", safety: 5, parking: 5, cleanliness: 5, cost: 3, environmental: 5, comment: "Best family outing in Durban. My kids couldn't believe the zebras were just walking around freely. Immaculate reserve. Secure, well-run, and reasonably priced." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/zebra,savanna,wildlife/all",
      photoCredit: "Photo: Unsplash",
      images: ["stainbank1", "stainbank2"],
      featured: true
    },
    {
      id: "burman-bush",
      name: "Burman Bush Nature Reserve",
      slug: "burman-bush-nature-reserve",
      tagline: "Coastal forest & bird hides in Morningside",
      description: "Burman Bush is a 50-hectare coastal forest reserve in the heart of Morningside, Durban. After a comprehensive security upgrade — including perimeter fencing, access-controlled gates, daily dog patrols, and on-site rangers — the reserve has seen a major resurgence in visitors. A quiet sanctuary for birdwatchers, morning walkers, and photography enthusiasts.",
      hectares: 50,
      location: "Morningside, Durban",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.8412, lng: 31.0156 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Guarded Public Lot",
      parking_notes: "Guarded entry gate with active security personnel",
      hours: "06:00 – 18:00 Daily",
      phone: "+27 31 303 4160",
      website: null,
      tags: ["Free", "Birdwatching", "Coastal Forest", "Walking", "Photography"],
      hazards: ["Hike in groups, especially on weekends – historic safety issues now resolved with security upgrade"],
      regulations: ["Hike in groups recommended on weekends", "Keep dogs on leash", "No littering"],
      attractions: ["Coastal scarp forest", "Bird-watching hides", "Interpretive trails", "Dog patrol routes", "Morningside forest canopy"],
      reviews: [
        { user: "BirderMorningside", date: "2026-06-01", safety: 4, parking: 4, cleanliness: 4, cost: 5, environmental: 4, comment: "Security upgrade has transformed this reserve! Dog patrols visible throughout. Spotted hadedas, sunbirds, and a fiscal shrike at the hide. Highly recommend." },
        { user: "DailyWalker_DBN", date: "2026-05-20", safety: 4, parking: 4, cleanliness: 4, cost: 5, environmental: 4, comment: "Go early for the best bird sightings. The new fencing and guards make it feel very safe now. Much better than a few years ago. Free and beautiful." },
        { user: "InterpretiveTrailFan", date: "2026-05-02", safety: 3, parking: 3, cleanliness: 3, cost: 5, environmental: 4, comment: "Interpretive trail signs need updating. Some information boards are damaged. But the forest itself is lovely. Security definitely improved. Walk in groups to be safe." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/forest,birds,path/all",
      photoCredit: "Photo: Unsplash",
      images: ["burman1", "burman2"],
      featured: false
    },
    {
      id: "giba-gorge-ggep",
      name: "Giba Gorge Environmental Precinct (GGEP)",
      slug: "giba-gorge-environmental-precinct",
      tagline: "400ha of community-protected scarp forest",
      description: "The Giba Gorge Environmental Precinct is a non-profit community conservation project covering 400 hectares of high-biodiversity scarp forest and open grasslands. Secured by the Winston Park Guardians who run regular security patrols. Free access with donation encouraged. Separate from the MTB Park – this is the wild, natural corridor of the gorge.",
      hectares: 400,
      location: "Winston Park, Pinetown",
      management: "Non-Profit Community (Winston Park Guardians)",
      coordinates: { lat: -29.7923, lng: 30.8534 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Guarded Public Lot",
      parking_notes: "Community-managed parking with volunteer guardian oversight",
      hours: "Sunrise – Sunset Daily",
      phone: null,
      website: null,
      tags: ["Free", "Conservation", "Hiking", "Birdwatching", "Community"],
      hazards: ["Some unmarked trails – download map before visiting", "Steep gorge terrain"],
      regulations: ["Donations strongly encouraged to fund guardian patrols", "Leave no trace", "No fires"],
      attractions: ["400ha natural scarp forest", "Community guardian patrols", "High biodiversity", "Natural gorge views", "Birding hotspot"],
      reviews: [
        { user: "ConservationHiker", date: "2026-05-25", safety: 4, parking: 3, cleanliness: 5, cost: 5, environmental: 5, comment: "Incredible that this is free. The Winston Park Guardians do an amazing job keeping it safe and clean. Donate generously – these volunteers deserve support." },
        { user: "NaturalistKZN", date: "2026-05-08", safety: 4, parking: 3, cleanliness: 5, cost: 5, environmental: 5, comment: "Found 3 rare orchid species on the gorge slopes! The community management model is inspirational. Dense, beautiful forest. Some trails are rough – bring good shoes." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/forest,conservation,green/all",
      photoCredit: "Photo: Unsplash",
      images: ["ggep1", "ggep2"],
      featured: false
    },
    {
      id: "pigeon-valley",
      name: "Pigeon Valley Nature Reserve",
      slug: "pigeon-valley-nature-reserve",
      tagline: "Tiny Glenwood gem — home of the Spotted Ground Thrush",
      description: "Pigeon Valley is a small but ecologically rich 9-hectare pocket of coastal scarp forest in Glenwood, Durban. It is one of the best birding spots in the city and the most reliable place in South Africa to see the rare and endangered Spotted Ground Thrush during winter. The reserve protects a number of large, old-growth trees and indigenous forest species.",
      hectares: 9,
      location: "Glenwood, Durban",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.8639, lng: 30.9886 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Street and small entrance parking on Princess Alice Avenue — not formally guarded, visit in groups",
      hours: "07:00 – 16:00 Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Birdwatching", "Coastal Forest", "Photography"],
      hazards: ["Limited security — visit in groups and avoid valuables on display", "Muddy paths after rain"],
      regulations: ["Stay on marked paths", "No pets", "No littering"],
      attractions: ["Spotted Ground Thrush (winter)", "Old-growth indigenous trees", "Forest birding trails", "Butterfly diversity"],
      reviews: [
        { user: "GlenwoodBirder", date: "2026-05-22", safety: 3, parking: 3, cleanliness: 4, cost: 5, environmental: 5, comment: "A magical little forest in the middle of the city. Saw the Spotted Ground Thrush in July last year. Best to go with a birding group — parking is on the street so keep an eye on your car." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/forest,bird,thrush/all",
      photoCredit: "Photo: Unsplash",
      images: ["pigeon1", "pigeon2"],
      featured: false
    },
    {
      id: "durban-botanic-gardens",
      name: "Durban Botanic Gardens",
      slug: "durban-botanic-gardens",
      tagline: "Africa's oldest surviving botanic garden",
      description: "Established in 1849, the Durban Botanic Gardens is the oldest surviving botanical garden in Africa. Spread over 15 hectares on the Berea, it features a renowned orchid house, a cycad collection of global importance, a sunken garden, tea garden, and sweeping lawns. A peaceful, family-friendly green space with excellent security and facilities in the heart of the city.",
      hectares: 15,
      location: "Berea, Durban",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.8447, lng: 31.0036 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Guarded Public Lot",
      parking_notes: "Guarded parking at the Sydenham Road entrance",
      hours: "07:30 – 17:15 Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Family", "Gardens", "Picnic", "Accessible"],
      hazards: ["Busy on weekends — arrive early"],
      regulations: ["No pets allowed", "No fishing in ponds", "No bicycles on lawns"],
      attractions: ["Ernest Thorp Orchid House", "Rare cycad collection", "Sunken garden", "Tea Garden restaurant", "Garden of the Senses"],
      reviews: [
        { user: "BereaFamily", date: "2026-05-29", safety: 5, parking: 5, cleanliness: 5, cost: 5, environmental: 5, comment: "An absolute treasure. Beautifully maintained, safe, and free. The orchid house is stunning and the tea garden does a lovely breakfast. Perfect for kids and grandparents alike." },
        { user: "OrchidLover_ZA", date: "2026-04-27", safety: 5, parking: 4, cleanliness: 5, cost: 5, environmental: 5, comment: "The cycad collection is world-class. Immaculate gardens, friendly staff, and very secure. One of Durban's best-kept public spaces." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/botanical,garden,orchid/all",
      photoCredit: "Photo: Unsplash",
      images: ["botanic1", "botanic2"],
      featured: true
    },
    {
      id: "new-germany",
      name: "New Germany Nature Reserve",
      slug: "new-germany-nature-reserve",
      tagline: "Grassland & forest trails above the Aller River",
      description: "New Germany Nature Reserve protects roughly 63 hectares of grassland, wetland, and riverine forest along the Aller River. A network of walking and mountain-biking trails winds through the reserve, which is a popular spot for trail runners, dog walkers, and birders in the western suburbs.",
      hectares: 63,
      location: "New Germany, Pinetown",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.7872, lng: 30.8869 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Entrance parking off Stafford Hill Road — keep valuables out of sight",
      hours: "06:00 – 18:00 Daily",
      phone: "+27 31 705 1011",
      website: null,
      tags: ["Free", "Hiking", "Mountain Biking", "Trail Running", "Birdwatching"],
      hazards: ["Some isolated trails — visit in groups", "Long grass in summer (snakes)"],
      regulations: ["Dogs on leash", "No fires", "Stay on marked trails"],
      attractions: ["Aller River trails", "Grassland birding", "MTB single-track", "Wildflowers in spring"],
      reviews: [
        { user: "WestSuburbRunner", date: "2026-05-17", safety: 3, parking: 3, cleanliness: 4, cost: 5, environmental: 4, comment: "Great network of trails close to home. I run here a few times a week. Quiet during the week so I go with a buddy. Lovely grassland birds and a peaceful river section." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/grassland,forest,river/all",
      photoCredit: "Photo: Unsplash",
      images: ["newgermany1", "newgermany2"],
      featured: false
    },
    {
      id: "roosfontein",
      name: "Roosfontein Nature Reserve",
      slug: "roosfontein-nature-reserve",
      tagline: "Grassland ridge with sweeping valley views",
      description: "Proclaimed in 1985, Roosfontein Nature Reserve covers around 94 hectares of grassland, wetland, and pockets of forest straddling the ridge between Manor Gardens, Queensburgh, and Westville. It offers open walking trails with excellent views over the Umbilo and Mlazi valleys, and is valued for its grassland bird and wildflower diversity.",
      hectares: 94,
      location: "Manor Gardens / Queensburgh",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.8344, lng: 30.9261 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Informal entrance parking — not guarded, visit in groups",
      hours: "Sunrise – Sunset Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Hiking", "Birdwatching", "Grassland", "Views"],
      hazards: ["Limited security — go in groups, keep valuables hidden", "Open grassland — minimal shade"],
      regulations: ["No fires", "Dogs on leash", "Stay on paths"],
      attractions: ["Ridge-top valley views", "Grassland birds", "Spring wildflowers", "Wetland sections"],
      reviews: [
        { user: "RidgeWalker_DBN", date: "2026-05-11", safety: 3, parking: 2, cleanliness: 3, cost: 5, environmental: 4, comment: "The views over the valley are fantastic and the grassland is full of birds. It's a bit wild and unguarded so I always walk here with friends, never alone. Free and underrated." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/grassland,hills,valley/all",
      photoCredit: "Photo: Unsplash",
      images: ["roosfontein1", "roosfontein2"],
      featured: false
    },
    {
      id: "springside",
      name: "Springside Nature Reserve",
      slug: "springside-nature-reserve",
      tagline: "Hillcrest's peaceful grassland & wetland walk",
      description: "Springside Nature Reserve is a small, well-loved 9-hectare reserve in Hillcrest, managed in partnership with the local conservancy. It protects mistbelt grassland, a wetland, and small forest patches, with gentle looping trails ideal for families and casual walkers. A community 'Friends of Springside' group keeps the trails in excellent shape.",
      hectares: 9,
      location: "Hillcrest",
      management: "eThekwini Municipality & Friends of Springside",
      coordinates: { lat: -29.7785, lng: 30.7708 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Small entrance lot off Kirtlington Road",
      hours: "Sunrise – Sunset Daily",
      phone: null,
      website: null,
      tags: ["Free", "Family", "Birdwatching", "Wetland", "Walking"],
      hazards: ["Boggy sections after rain"],
      regulations: ["Dogs on leash", "No fires", "Donations to Friends of Springside welcomed"],
      attractions: ["Mistbelt grassland", "Wetland boardwalk", "Spring wildflowers", "Family-friendly loops"],
      reviews: [
        { user: "HillcrestWalker", date: "2026-05-24", safety: 4, parking: 4, cleanliness: 5, cost: 5, environmental: 4, comment: "A lovely little reserve kept beautifully by the Friends group. Perfect short walk with the kids and dog. Peaceful, safe during daylight, and the wildflowers in spring are gorgeous." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/wetland,grassland,nature/all",
      photoCredit: "Photo: Unsplash",
      images: ["springside1", "springside2"],
      featured: false
    },
    {
      id: "iphithi",
      name: "Iphithi Nature Reserve",
      slug: "iphithi-nature-reserve",
      tagline: "Community-run forest & grassland in Gillitts",
      description: "Iphithi Nature Reserve is a community-managed 10-hectare reserve in Gillitts protecting indigenous forest and mistbelt grassland. Run by a dedicated volunteer trust, it has a small network of well-marked trails, an indigenous nursery, and is a favourite for gentle family walks and birding in the Upper Highway area.",
      hectares: 10,
      location: "Gillitts",
      management: "Iphithi Community Trust",
      coordinates: { lat: -29.7948, lng: 30.7972 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Entrance parking off Iphithi Road — visit during daylight",
      hours: "Sunrise – Sunset Daily",
      phone: null,
      website: null,
      tags: ["Free", "Family", "Birdwatching", "Forest", "Community"],
      hazards: ["Quiet during weekdays — go in groups"],
      regulations: ["Dogs on leash", "Donations welcomed", "Stay on marked trails"],
      attractions: ["Indigenous forest trails", "Grassland birding", "Indigenous plant nursery", "Family walks"],
      reviews: [
        { user: "UpperHighwayMom", date: "2026-05-19", safety: 4, parking: 3, cleanliness: 5, cost: 5, environmental: 5, comment: "Such a well-cared-for little reserve. The volunteers do an incredible job. Easy trails for little legs and lovely birdlife. We always go as a family on weekend mornings." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/indigenous,forest,trail/all",
      photoCredit: "Photo: Unsplash",
      images: ["iphithi1", "iphithi2"],
      featured: false
    },
    {
      id: "beachwood-mangroves",
      name: "Beachwood Mangroves Nature Reserve",
      slug: "beachwood-mangroves-nature-reserve",
      tagline: "Boardwalk through a living mangrove estuary",
      description: "Beachwood Mangroves Nature Reserve protects 76 hectares of mangrove forest at the mouth of the Umgeni River in Durban North. A raised boardwalk and guided trails lead through one of the few accessible mangrove systems in South Africa, home to fiddler crabs, mudskippers, and a rich diversity of estuarine birds. Managed by Ezemvelo KZN Wildlife.",
      hectares: 76,
      location: "Durban North (Umgeni River mouth)",
      management: "Ezemvelo KZN Wildlife",
      coordinates: { lat: -29.8033, lng: 31.0397 },
      payment_method: "Card Only",
      entry_fee_adult: 40,
      entry_fee_child: 20,
      parking_type: "Guarded Public Lot",
      parking_notes: "Gated reserve parking — access controlled by Ezemvelo staff",
      hours: "06:00 – 16:00 (Closed on spring high tides — call ahead)",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Mangroves", "Birdwatching", "Boardwalk", "Educational", "Photography"],
      hazards: ["Tidal — sections close on high spring tides", "Mosquitoes near dusk — bring repellent"],
      regulations: ["No collecting of crabs or shells", "Stay on the boardwalk", "No pets"],
      attractions: ["Mangrove boardwalk", "Fiddler crabs & mudskippers", "Estuarine birding", "Guided eco-walks"],
      reviews: [
        { user: "EstuaryExplorer", date: "2026-05-21", safety: 4, parking: 4, cleanliness: 4, cost: 4, environmental: 5, comment: "Fascinating ecosystem you can't see anywhere else nearby. The boardwalk takes you right into the mangroves. Call ahead to check the tide. Great for kids learning about estuaries." }
      ],
      alerts: [
        { category: "Tidal Closure", severity: "Low", details: "Lower boardwalk sections may be closed during spring high tides. Phone the reserve before visiting to confirm access.", active: true }
      ],
      photo: "https://loremflickr.com/1000/500/mangrove,estuary,boardwalk/all",
      photoCredit: "Photo: Unsplash",
      images: ["beachwood1", "beachwood2"],
      featured: false
    },
    {
      id: "bluff-nature-reserve",
      name: "Bluff Nature Reserve",
      slug: "bluff-nature-reserve",
      tagline: "Coastal pan & dune forest on the Bluff",
      description: "Bluff Nature Reserve protects 45 hectares of coastal dune forest, grassland, and a large freshwater pan on the Bluff peninsula south of Durban harbour. Bird hides overlook the pan, which attracts a wide range of waterbirds, while easy trails wind through the surrounding forest. A quiet, accessible reserve managed by Ezemvelo KZN Wildlife.",
      hectares: 45,
      location: "Bluff, Durban",
      management: "Ezemvelo KZN Wildlife",
      coordinates: { lat: -29.9242, lng: 31.0103 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Entrance parking off Tara Road — visit during daylight, go in groups",
      hours: "06:00 – 17:00 Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Birdwatching", "Dune Forest", "Bird Hides", "Walking"],
      hazards: ["Quiet reserve — visit in groups", "Long grass in summer"],
      regulations: ["No fishing in the pan", "Dogs on leash", "Stay on trails"],
      attractions: ["Freshwater pan & bird hides", "Coastal dune forest", "Waterbird diversity", "Easy walking loops"],
      reviews: [
        { user: "BluffBirder", date: "2026-05-13", safety: 3, parking: 3, cleanliness: 4, cost: 5, environmental: 4, comment: "The bird hides over the pan are excellent — herons, kingfishers, and weavers galore. It's a peaceful spot. I go with my birding club rather than alone. Free and worth it." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/coastal,forest,pan/all",
      photoCredit: "Photo: Unsplash",
      images: ["bluff1", "bluff2"],
      featured: false
    },
    {
      id: "umhlanga-lagoon",
      name: "uMhlanga Lagoon Nature Reserve",
      slug: "umhlanga-lagoon-nature-reserve",
      tagline: "Dune forest, lagoon & beach below the lighthouse",
      description: "uMhlanga Lagoon Nature Reserve protects 26 hectares of coastal dune forest and the Ohlanga River lagoon just north of the famous Umhlanga lighthouse. A boardwalk and forest trails connect the lagoon to a pristine stretch of beach, making it one of the most scenic and accessible coastal reserves in Durban. Managed by Ezemvelo KZN Wildlife.",
      hectares: 26,
      location: "Umhlanga Rocks",
      management: "Ezemvelo KZN Wildlife",
      coordinates: { lat: -29.7233, lng: 31.0883 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Street parking near the lighthouse and Lagoon Drive — busy and generally safe in the day",
      hours: "06:00 – 18:00 Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Beach", "Dune Forest", "Birdwatching", "Family"],
      hazards: ["Lagoon mouth can be deep — no swimming at the river mouth", "Busy parking on weekends"],
      regulations: ["No pets on the beach section", "Stay on the boardwalk in the forest", "No littering"],
      attractions: ["Ohlanga lagoon boardwalk", "Dune forest trail", "Umhlanga lighthouse views", "Coastal birding", "Pristine beach"],
      reviews: [
        { user: "UmhlangaLocal", date: "2026-06-02", safety: 4, parking: 3, cleanliness: 4, cost: 5, environmental: 5, comment: "One of the most beautiful walks in Durban — through the dune forest, over the lagoon, and onto the beach by the lighthouse. Gets busy on weekends so come early. Free and stunning." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/lagoon,beach,dune/all",
      photoCredit: "Photo: Unsplash",
      images: ["umhlanga1", "umhlanga2"],
      featured: true
    },
    {
      id: "silverglen",
      name: "Silverglen Nature Reserve",
      slug: "silverglen-nature-reserve",
      tagline: "Chatsworth bushveld, dam & medicinal plant nursery",
      description: "Silverglen Nature Reserve covers around 220 hectares of coastal bushveld, grassland, and a dam in Chatsworth. It is well known for its medicinal plant nursery, which propagates indigenous species used in traditional medicine, and offers walking trails, fishing at the dam, and a variety of bird and small mammal species.",
      hectares: 220,
      location: "Chatsworth",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.9242, lng: 30.8917 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Guarded Public Lot",
      parking_notes: "Reserve entrance parking off Silverglen Drive",
      hours: "07:00 – 16:00 Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Hiking", "Dam", "Birdwatching", "Educational"],
      hazards: ["Long grass in summer (snakes)", "Visit in groups on quieter trails"],
      regulations: ["Fishing permit required for the dam", "No plant collecting", "Dogs on leash"],
      attractions: ["Medicinal plant nursery", "Silverglen dam & fishing", "Bushveld trails", "Indigenous birding"],
      reviews: [
        { user: "ChatsworthHiker", date: "2026-05-16", safety: 4, parking: 4, cleanliness: 4, cost: 5, environmental: 4, comment: "A surprisingly large and varied reserve. The medicinal plant nursery is really interesting and the dam is peaceful. Good trails — we go as a group. A genuine hidden gem in the south." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/bushveld,dam,nature/all",
      photoCredit: "Photo: Unsplash",
      images: ["silverglen1", "silverglen2"],
      featured: false
    },
    {
      id: "virginia-bush",
      name: "Virginia Bush Nature Reserve",
      slug: "virginia-bush-nature-reserve",
      tagline: "Last coastal forest remnant in Durban North",
      description: "Virginia Bush is a 50-hectare reserve protecting one of the last significant remnants of coastal lowland forest in Durban North. A shaded trail network loops through dense indigenous forest rich in birds, butterflies, and old-growth trees — a cool, green escape surrounded by suburbia.",
      hectares: 50,
      location: "Durban North",
      management: "eThekwini Municipality",
      coordinates: { lat: -29.7806, lng: 31.0383 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Entrance parking off Lansdowne Road — visit in groups",
      hours: "06:00 – 17:00 Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Birdwatching", "Coastal Forest", "Walking", "Photography"],
      hazards: ["Quiet forest — visit in groups, keep valuables hidden"],
      regulations: ["Stay on marked trails", "Dogs on leash", "No littering"],
      attractions: ["Coastal lowland forest", "Forest birding", "Butterfly diversity", "Old-growth trees"],
      reviews: [
        { user: "DurbanNorthWalker", date: "2026-05-09", safety: 3, parking: 3, cleanliness: 4, cost: 5, environmental: 5, comment: "A beautiful cool forest tucked into the suburbs. The birdlife is excellent. It's quiet so we always walk in a small group. Lovely to have this green lung in Durban North." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/coastal,forest,canopy/all",
      photoCredit: "Photo: Unsplash",
      images: ["virginia1", "virginia2"],
      featured: false
    },
    {
      id: "shongweni-dam",
      name: "Shongweni Dam & Nature Reserve",
      slug: "shongweni-dam-nature-reserve",
      tagline: "Cliffs, dam & game in a dramatic gorge",
      description: "Managed by Msinsi Holdings, Shongweni Dam and Nature Reserve covers a dramatic gorge landscape of cliffs, bushveld, and a large dam west of Durban. The reserve offers game viewing (including antelope, zebra, and hippo), abseiling, hiking, canoeing, and birding, and is near the popular weekend Shongweni Farmers Market.",
      hectares: 750,
      location: "Shongweni / Assagay",
      management: "Msinsi Holdings",
      coordinates: { lat: -29.8631, lng: 30.7186 },
      payment_method: "Cash & Card",
      entry_fee_adult: 50,
      entry_fee_child: 30,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Secured reserve parking inside the gated entrance",
      hours: "06:00 – 18:00 Daily",
      phone: "+27 31 769 1283",
      website: null,
      tags: ["Game Viewing", "Hiking", "Dam", "Canoeing", "Birdwatching"],
      hazards: ["Hippo and game present — keep distance", "Steep cliff edges", "Hot in summer — carry water"],
      regulations: ["No swimming in the dam (hippo)", "Stay in vehicle near large game where signed", "Permit required for canoeing"],
      attractions: ["Shongweni dam & gorge cliffs", "Antelope, zebra & hippo", "Abseiling & rock climbing", "Canoeing & birding", "Nearby Shongweni Market"],
      reviews: [
        { user: "GorgeAdventurer", date: "2026-05-26", safety: 4, parking: 5, cleanliness: 4, cost: 4, environmental: 5, comment: "Dramatic scenery — the cliffs and dam are spectacular. Saw zebra and plenty of birds. Parking inside is secure and the gate is controlled. Combine it with the Saturday market for a great day out." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/gorge,dam,cliffs/all",
      photoCredit: "Photo: Unsplash",
      images: ["shongweni1", "shongweni2"],
      featured: true
    },
    {
      id: "hazelmere-dam",
      name: "Hazelmere Dam & Resort",
      slug: "hazelmere-dam-resort",
      tagline: "Watersports & fishing dam north of Durban",
      description: "Hazelmere Dam, managed by Msinsi Holdings, lies on the Mdloti River near Verulam north of Durban. The reserve is popular for watersports, fishing, picnicking, and birding, with a resort and secure day-visitor facilities. Open grassland and bushveld around the dam support a variety of birds and small game.",
      hectares: 500,
      location: "Verulam (Mdloti River)",
      management: "Msinsi Holdings",
      coordinates: { lat: -29.5969, lng: 31.0344 },
      payment_method: "Cash & Card",
      entry_fee_adult: 40,
      entry_fee_child: 25,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Secured day-visitor parking inside the gated resort",
      hours: "06:00 – 18:00 Daily",
      phone: "+27 32 533 0303",
      website: null,
      tags: ["Watersports", "Fishing", "Picnic", "Birdwatching", "Family"],
      hazards: ["Open water — watersports at own risk", "Sun exposure — limited shade"],
      regulations: ["Fishing and boating permits required", "No glass at picnic sites", "Life jackets for watercraft"],
      attractions: ["Dam watersports", "Bank & boat fishing", "Picnic lawns", "Grassland birding"],
      reviews: [
        { user: "AnglerNorth", date: "2026-05-14", safety: 4, parking: 5, cleanliness: 4, cost: 4, environmental: 4, comment: "Reliable fishing spot and great for a family picnic by the water. Secure parking and controlled entry. Gets busy in school holidays but well managed. Bring a gazebo for shade." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/dam,lake,fishing/all",
      photoCredit: "Photo: Unsplash",
      images: ["hazelmere1", "hazelmere2"],
      featured: false
    },
    {
      id: "inanda-dam",
      name: "Inanda Dam & Nature Reserve",
      slug: "inanda-dam-nature-reserve",
      tagline: "Largest dam near Durban — watersports & game",
      description: "Inanda Dam, managed by Msinsi Holdings, is the largest dam in the Durban area, set on the uMngeni River northwest of the city. The surrounding reserve offers game viewing, watersports, fishing, hiking, and a resort. It is a popular venue for rowing and paddling events and supports zebra, antelope, and abundant birdlife along its shores.",
      hectares: 1100,
      location: "Inanda (uMngeni River)",
      management: "Msinsi Holdings",
      coordinates: { lat: -29.6906, lng: 30.8675 },
      payment_method: "Cash & Card",
      entry_fee_adult: 45,
      entry_fee_child: 25,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Secured day-visitor parking inside the gated reserve",
      hours: "06:00 – 18:00 Daily",
      phone: "+27 31 326 7300",
      website: null,
      tags: ["Watersports", "Game Viewing", "Fishing", "Hiking", "Birdwatching"],
      hazards: ["Open water — watersports at own risk", "Game present — keep distance", "Carry water in summer"],
      regulations: ["Boating & fishing permits required", "Life jackets compulsory on the water", "No off-trail driving"],
      attractions: ["Largest dam near Durban", "Rowing & paddling waters", "Zebra & antelope", "Shoreline birding", "Resort facilities"],
      reviews: [
        { user: "PaddlerKZN", date: "2026-05-23", safety: 4, parking: 5, cleanliness: 4, cost: 4, environmental: 5, comment: "Huge, beautiful dam — fantastic for paddling and there's game around the shore too. Entry is controlled and parking secure. A proper day-trip destination just outside the city." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/dam,reservoir,hills/all",
      photoCredit: "Photo: Unsplash",
      images: ["inanda1", "inanda2"],
      featured: false
    },
    {
      id: "hawaan-forest",
      name: "Hawaan Forest",
      slug: "hawaan-forest",
      tagline: "Ancient dune forest above Umhlanga",
      description: "The Hawaan Forest is a privately protected ancient coastal dune forest above Umhlanga, conserved with the support of WESSA and the Hawaan Conservancy. Access is by guided walk only, protecting its rare trees and its populations of blue and red duiker. One of the oldest and most botanically significant forests in the region.",
      hectares: 70,
      location: "Umhlanga",
      management: "WESSA / Hawaan Conservancy",
      coordinates: { lat: -29.7256, lng: 31.0814 },
      payment_method: "Card Only",
      entry_fee_adult: 80,
      entry_fee_child: 40,
      parking_type: "Fenced Guarded Interior",
      parking_notes: "Access by booked guided walk only — secure meeting point parking",
      hours: "By guided walk / booking only",
      phone: null,
      website: null,
      tags: ["Guided Walks", "Ancient Forest", "Birdwatching", "Conservation", "Educational"],
      hazards: ["Access by guided walk only — no unaccompanied entry"],
      regulations: ["Entry by booked guided walk only", "No collecting of any plant material", "Stay with your guide"],
      attractions: ["Ancient coastal dune forest", "Rare endemic trees", "Blue & red duiker", "Expert-guided eco-walks"],
      reviews: [
        { user: "ForestEnthusiast", date: "2026-05-18", safety: 5, parking: 5, cleanliness: 5, cost: 3, environmental: 5, comment: "A privilege to walk through such an ancient forest. The guides are incredibly knowledgeable about the rare trees and we even glimpsed a duiker. Booking essential — well worth it." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/ancient,forest,trees/all",
      photoCredit: "Photo: Unsplash",
      images: ["hawaan1", "hawaan2"],
      featured: false
    },
    {
      id: "amanzimtoti-bird-sanctuary",
      name: "Amanzimtoti Bird Sanctuary",
      slug: "amanzimtoti-bird-sanctuary",
      tagline: "Riverside bird hides south of Durban",
      description: "The Amanzimtoti Bird Sanctuary is a small riverine reserve along the Amanzimtoti River on the South Coast. Its bird hides and short trails make it a peaceful birding spot where waterbirds, kingfishers, and weavers can be observed close to the heart of Amanzimtoti.",
      hectares: 12,
      location: "Amanzimtoti",
      management: "eThekwini Municipality",
      coordinates: { lat: -30.0508, lng: 30.8819 },
      payment_method: "Free",
      entry_fee_adult: 0,
      entry_fee_child: 0,
      parking_type: "Open Public Lot",
      parking_notes: "Small entrance parking off Umdoni Road — visit during daylight",
      hours: "07:00 – 17:00 Daily",
      phone: "+27 31 322 4021",
      website: null,
      tags: ["Free", "Birdwatching", "Bird Hides", "River Walk", "Family"],
      hazards: ["River can flood after heavy rain", "Visit in groups midweek"],
      regulations: ["Quiet in the hides", "No feeding birds", "Dogs on leash"],
      attractions: ["Riverside bird hides", "Kingfishers & weavers", "Short family trail", "Waterbird diversity"],
      reviews: [
        { user: "TotiBirder", date: "2026-05-10", safety: 4, parking: 3, cleanliness: 4, cost: 5, environmental: 4, comment: "A lovely little stop for birders on the South Coast. The hides are well placed over the river and you can rack up a good species list in an hour. Quiet and free — go in the morning." }
      ],
      alerts: [],
      photo: "https://loremflickr.com/1000/500/river,bird,sanctuary/all",
      photoCredit: "Photo: Unsplash",
      images: ["toti1", "toti2"],
      featured: false
    }
  ]
};

// Calculate weighted desirability index
function calculateDesirabilityIndex(location) {
  if (!location.reviews || location.reviews.length === 0) return 3.0;

  const n = location.reviews.length;
  const avg = (key) => location.reviews.reduce((s, r) => s + r[key], 0) / n;

  const S = avg('safety');
  const P = avg('parking');
  const C = avg('cleanliness');
  const F = avg('cost');
  const E = avg('environmental');

  // D_i = ws*S + wp*P + we*E + wc*C - wf*F
  const D = (0.35 * S) + (0.25 * P) + (0.15 * E) + (0.15 * C) - (0.10 * F);
  return Math.round(D * 100) / 100;
}

function getAverageScore(location, key) {
  if (!location.reviews || location.reviews.length === 0) return 0;
  return Math.round(location.reviews.reduce((s, r) => s + r[key], 0) / location.reviews.length * 10) / 10;
}

// Enrich locations with computed scores
KZN_DATA.locations.forEach(loc => {
  loc.desirabilityIndex = calculateDesirabilityIndex(loc);
  loc.avgSafety = getAverageScore(loc, 'safety');
  loc.avgParking = getAverageScore(loc, 'parking');
  loc.avgCleanliness = getAverageScore(loc, 'cleanliness');
  loc.avgCost = getAverageScore(loc, 'cost');
  loc.avgEnvironmental = getAverageScore(loc, 'environmental');
  loc.activeAlerts = loc.alerts.filter(a => a.active).length;
  loc.reviewCount = loc.reviews.length;
});
